"""Tests for write-path prose normalisation.

Each structural branch gets a case that would fail loudly if the branch stopped firing, because
the defect this guards against is exactly a check that silently does nothing. See VHK-DEC-133.
"""

import os

import pytest

from obsidian_self_mcp.prose import normalize_prose


@pytest.fixture(autouse=True)
def _enabled(request, monkeypatch):
    """Normalisation is opt-in, so the behaviour tests set the flag explicitly.

    The flag tests manage the environment themselves and opt out of this fixture.
    """
    if "flag" in request.node.name:
        return
    monkeypatch.setenv("OBSIDIAN_NORMALIZE_PROSE", "1")


def test_joins_a_hard_wrapped_paragraph():
    src = "This paragraph is hard\nwrapped across three\nlines and must join."
    assert normalize_prose(src) == "This paragraph is hard wrapped across three lines and must join."


def test_preserves_paragraph_breaks():
    src = "First para\nwrapped.\n\nSecond para\nwrapped."
    assert normalize_prose(src) == "First para wrapped.\n\nSecond para wrapped."


def test_frontmatter_is_verbatim():
    src = '---\ntype: WorkNote\ntags:\n  - a\n  - b\n---\n\nBody text\nwrapped.'
    out = normalize_prose(src)
    assert out.startswith('---\ntype: WorkNote\ntags:\n  - a\n  - b\n---')
    assert "Body text wrapped." in out


def test_horizontal_rule_in_body_is_not_read_as_frontmatter():
    src = "Intro line\nwrapped.\n\n---\n\nAfter the rule\nalso wrapped."
    out = normalize_prose(src)
    assert "Intro line wrapped." in out
    assert "\n---\n" in out
    assert "After the rule also wrapped." in out


def test_backtick_fence_is_verbatim():
    src = "```bash\nline one\nline two\n```"
    assert normalize_prose(src) == src


def test_tilde_fence_containing_backticks_does_not_terminate_early():
    src = "~~~python\ntilde fence with ``` inside\nmust not terminate early\n~~~\n\nAfter\nwrapped."
    out = normalize_prose(src)
    assert "tilde fence with ``` inside\nmust not terminate early" in out
    assert "After wrapped." in out


def test_table_rows_stay_separate():
    src = "| a | b |\n|---|---|\n| 1 | 2 |"
    assert normalize_prose(src) == src


def test_headings_stay_separate():
    src = "# Heading\nBody line\nwrapped."
    assert normalize_prose(src) == "# Heading\nBody line wrapped."


def test_blockquote_lines_stay_broken():
    src = "> a blockquote line\n> that must stay broken"
    assert normalize_prose(src) == src


def test_indented_code_stays_broken():
    src = "    indented code\n    must stay broken"
    assert normalize_prose(src) == src


def test_list_item_continuation_rejoins_but_items_stay_separate():
    src = "- a list item that is hard\n  wrapped and should rejoin\n- a second item"
    assert normalize_prose(src) == "- a list item that is hard wrapped and should rejoin\n- a second item"


def test_link_only_lines_are_never_joined():
    """The Zoottelkeeper case: one space-indented wikilink per line, 90-100 chars each.

    Before the guard this collapsed _Index_of_Lib.md from 39 lines to 10.
    """
    src = (
        "%% Zoottelkeeper: Beginning of the autogenerated index file list  %%\n"
        " [[Projects/Simons AI (SAI)/PAI Hook and Tool Reference/Lib/artefact-cr|artefact-cr]]\n"
        " [[Projects/Simons AI (SAI)/PAI Hook and Tool Reference/Lib/cstate-oq|cstate-oq]]\n"
        "%% Zoottelkeeper: End of the autogenerated index file list  %%"
    )
    assert normalize_prose(src) == src


def test_link_only_line_does_not_absorb_the_line_after_it():
    src = " [[Some/Long/Path/note|note]]\nplain text after"
    assert normalize_prose(src) == src


def test_markdown_link_only_line_is_also_protected():
    src = "[text](Folder/Name.md)\n[other](Folder/Other.md)"
    assert normalize_prose(src) == src


def test_is_idempotent():
    src = "A paragraph hard\nwrapped over lines.\n\n- item one\n  continued\n\n| a | b |\n|---|---|"
    once = normalize_prose(src)
    assert normalize_prose(once) == once


def test_content_is_preserved_word_for_word():
    src = "Some prose that is\nwrapped over several\nlines here.\n\n- and a list\n  continuation too"
    assert normalize_prose(src).split() == src.split()


def test_already_unwrapped_content_is_a_noop():
    src = "One long line of prose that was never wrapped at all.\n\nAnother one."
    assert normalize_prose(src) == src


def test_empty_content_is_returned_unchanged():
    assert normalize_prose("") == ""


def test_env_flag_absent_means_DISABLED():
    """Opt-in. The repo is an editable install, so a default-on flag would change production
    write behaviour the moment the file is saved."""
    os.environ.pop("OBSIDIAN_NORMALIZE_PROSE", None)
    src = "This is hard\nwrapped."
    assert normalize_prose(src) == src


def test_env_flag_set_to_one_enables():
    os.environ["OBSIDIAN_NORMALIZE_PROSE"] = "1"
    try:
        assert normalize_prose("a\nb") == "a b"
    finally:
        del os.environ["OBSIDIAN_NORMALIZE_PROSE"]


def test_any_other_flag_value_is_disabled():
    for v in ("0", "true", "yes", ""):
        os.environ["OBSIDIAN_NORMALIZE_PROSE"] = v
        try:
            assert normalize_prose("a\nb") == "a\nb", f"value {v!r} should not enable"
        finally:
            del os.environ["OBSIDIAN_NORMALIZE_PROSE"]
