"""Where FTS5 trigram case folding and Python's `re.IGNORECASE` disagree.

The query path confirms every hit with a case-insensitive Python regex, but it
only confirms the candidates FTS5 hands it. Where Python treats two characters
as the same letter and the trigram tokenizer does not, the index would
under-select and the hit would be missed without notice: `istanbul` against a
note containing `İstanbul`, for example.

Each such pair (query character q, note character d) is closed from one side:

- d is non-ASCII: a note containing any `FOLD_ODD` character is flagged at
  index time, and flagged notes are always candidates. Measured on production
  2026-10-01: 3 of 11,731 notes carry one.
- d is ASCII: only `İ` and `ı` fold to an ASCII letter here, and flagging every
  note with an `i` would flag everything, so a query containing one of
  `SCAN_QUERY_CHARS` reads every note in scope instead.

The tables are generated by `compute_fold_sets()`, which compares the two
foldings directly; a test re-runs it, so a Python or SQLite upgrade that moves
either folding fails the suite rather than missing hits silently.
"""

from __future__ import annotations

import re
import sqlite3

FOLD_ODD_RANGES = (
    (0x0130, 0x0131), (0x025C, 0x025C), (0x0261, 0x0261), (0x026A, 0x026A),
    (0x026C, 0x026C), (0x0282, 0x0282), (0x0287, 0x0287), (0x029D, 0x029E),
    (0x037F, 0x037F), (0x0390, 0x0390), (0x03B0, 0x03B0), (0x03F3, 0x03F3),
    (0x0412, 0x0412), (0x0414, 0x0414), (0x041E, 0x041E), (0x0421, 0x0422),
    (0x042A, 0x042A), (0x0432, 0x0432), (0x0434, 0x0434), (0x043E, 0x043E),
    (0x0441, 0x0442), (0x044A, 0x044A), (0x0462, 0x0463), (0x0528, 0x052F),
    (0x10D0, 0x10FA), (0x10FD, 0x10FF), (0x13A0, 0x13F5), (0x13F8, 0x13FD),
    (0x1C80, 0x1C88), (0x1C90, 0x1CBA), (0x1CBD, 0x1CBF), (0x1D8E, 0x1D8E),
    (0x1FD3, 0x1FD3), (0x1FE3, 0x1FE3), (0x2C2F, 0x2C2F), (0x2C5F, 0x2C5F),
    (0xA64A, 0xA64B), (0xA698, 0xA69B), (0xA794, 0xA794), (0xA796, 0xA79F),
    (0xA7AB, 0xA7AE), (0xA7B0, 0xA7CA), (0xA7D0, 0xA7D1), (0xA7D6, 0xA7D9),
    (0xA7F5, 0xA7F6), (0xAB53, 0xAB53), (0xAB70, 0xABBF), (0xFB05, 0xFB06),
    (0x104B0, 0x104D3), (0x104D8, 0x104FB), (0x10570, 0x1057A), (0x1057C, 0x1058A),
    (0x1058C, 0x10592), (0x10594, 0x10595), (0x10597, 0x105A1), (0x105A3, 0x105B1),
    (0x105B3, 0x105B9), (0x105BB, 0x105BC), (0x10C80, 0x10CB2), (0x10CC0, 0x10CF2),
    (0x118A0, 0x118DF), (0x16E40, 0x16E7F), (0x1E900, 0x1E943),
)
SCAN_QUERY_CHARS = frozenset("İı")  # İ ı

# Non-ASCII characters `re.IGNORECASE` treats as an ASCII letter. SQLite's
# LIKE folds ASCII only, so a short ASCII query must also take any note that
# holds one of these for a letter it contains.
ASCII_EQUIVALENTS = {
    "i": "İı",  # İ ı
    "k": "K",        # KELVIN SIGN
    "s": "ſ",        # LATIN SMALL LETTER LONG S
}


def ascii_query_equivalents(query: str) -> str:
    """The non-ASCII characters that can stand for a letter of `query`."""
    return "".join(sorted({c for ch in query.lower() for c in ASCII_EQUIVALENTS.get(ch, "")}))


def compute_ascii_equivalents() -> dict[str, str]:
    """Derive ASCII_EQUIVALENTS from the running Python. For the test.

    Candidates are the code points `re` itself would fold to ASCII (simple
    lowercase in range, or its extra-case table); each is then confirmed
    against every printable ASCII character with a real IGNORECASE match.
    """
    import _sre
    from re import _casefix

    candidates = {
        cp for cp in range(0x80, 0x110000)
        if not 0xD800 <= cp <= 0xDFFF and _sre.unicode_tolower(cp) < 0x80
    }
    for a in range(0x20, 0x7F):
        candidates.update(x for x in _casefix._EXTRA_CASES.get(a, ()) if x >= 0x80)
    out: dict[str, set[str]] = {}
    for cp in candidates:
        for a in map(chr, range(0x20, 0x7F)):
            if re.fullmatch(re.escape(a), chr(cp), re.IGNORECASE):
                out.setdefault(a.lower(), set()).add(chr(cp))
    return {a: "".join(sorted(s)) for a, s in out.items()}

_FOLD_ODD_RE = re.compile(
    "[" + "".join(
        re.escape(chr(a)) if a == b else f"{re.escape(chr(a))}-{re.escape(chr(b))}"
        for a, b in FOLD_ODD_RANGES
    ) + "]"
)


def has_fold_odd(text: str) -> bool:
    """True if `text` holds a character the trigram index may fail to match."""
    return _FOLD_ODD_RE.search(text) is not None


def needs_scan(query: str) -> bool:
    """True if FTS5 cannot be trusted to select candidates for `query`."""
    return not SCAN_QUERY_CHARS.isdisjoint(query)


def compute_fold_sets() -> tuple[set[int], set[int]]:
    """Derive (fold-odd note chars, scan-query chars) from the running Python and SQLite.

    Slow (seconds): walks every code point. For the test and for regenerating
    the tables above, never for a query.
    """
    import _sre
    from re import _casefix

    by_lower: dict[int, set[int]] = {}
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        by_lower.setdefault(_sre.unicode_tolower(cp), set()).add(cp)
    classes: dict[int, set[int]] = {}
    for lo, members in by_lower.items():
        group = set(members)
        for x in list(group) + [lo]:
            group.update(_casefix._EXTRA_CASES.get(x, ()))
        for x in group:
            classes.setdefault(x, set()).update(group)

    conn = sqlite3.connect(":memory:")
    conn.execute("CREATE VIRTUAL TABLE t USING fts5(b, tokenize='trigram')")
    odd: set[int] = set()
    scan: set[int] = set()
    for q, members in classes.items():
        for d in members:
            if d == q or not re.fullmatch(re.escape(chr(q)), chr(d), re.IGNORECASE):
                continue
            conn.execute("DELETE FROM t")
            conn.execute("INSERT INTO t(rowid, b) VALUES(1, ?)", (chr(d) * 3,))
            if conn.execute(
                "SELECT 1 FROM t WHERE t MATCH ?", ('"' + chr(q) * 3 + '"',)
            ).fetchone():
                continue
            (odd if d >= 0x80 else scan).add(d if d >= 0x80 else q)
    conn.close()
    return odd, scan


def fold_odd_codepoints() -> set[int]:
    return {cp for a, b in FOLD_ODD_RANGES for cp in range(a, b + 1)}
